server:
  port: ${SERVER_PORT}
spring:
  application:
    name: backend
  config:
    import: file:.env[.properties]
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: 27017
      authentication-database: admin
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
app:
  weather-api-key: ${WEATHER_API_KEY}